import type { Metadata } from "next";
import "./globals.css";
import { createClient } from '@/utils/supabase/server'
import HeaderNotConnected from "./components/ui/HeaderNotConnected";
import HeaderConnected from "./components/ui/HeaderConnected";
import AIChat from "./components/ui/AIChat";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const supabase = await createClient()
  return (

    <html lang="en">
      <body
        className={`antialiased px-10 py-5`}
      >
        {(await supabase.auth.getSession())["data"]["session"]?<HeaderConnected />:<HeaderNotConnected />}
        {children}
        <AIChat />
      </body>
    </html>
  );
}
